[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]

[tool.setuptools_scm]
local_scheme = "no-local-version" # https://stackoverflow.com/questions/73605607/how-to-use-setuptools-scm

[tool.black]
